### ISSUE TITLE
Certificate authentication doesn't work with etcd v3

### ISSUE THREAD

**Issue by chobostar** [zalando/patroni#2036] opened 2021-08-17 16:16 UTC
**Describe the bug**
Patroni 2.1.0 tries to work with etcd using http requests. So if one tries to use TLS with Common Name authentication it will not work.

https://etcd.io/docs/v3.4/dev-guide/api_grpc_gateway/#notes
```
gRPC-gateway does not support authentication using TLS Common Name.
```

Here is discussion: https://github.com/etcd-io/etcd/issues/11970#issuecomment-687875315

**To Reproduce**
1. have a cert with CN:
```
$ openssl x509 -in /etc/ssl/patroni.pem  -text | grep Subject:
        Subject: L = <redacted>, O = <redacted>, OU = <redacted>, CN = patroni-client
```
2. enable client-tls-auth in etcd
3. add user and role `patroni-client` in etcd server, then enable auth
4. try to run patroni with:
```
etcd3:
  protocol: https
  cert: "/etc/ssl/patroni.pem"
  key: "/etc/ssl/patroni.key"
  cacert: "/etc/ssl/ca.pem"  
```

**Expected behavior**
patroni agent authenticated using etcd v3 as `patroni-client` user

**Screenshots**
no screenshots

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 12.3
- DCS (and its version): etcd 3.4.16

**Patroni configuration file**
```
---
name: test123-1
namespace: /patroni/
scope: test123
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.11.12.3:8008
  authentication:
    username: patroni
    password: "123"
bootstrap:
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 20
    maximum_lag_on_failover: 1048576
    master_start_timeout: 60
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        wal_level: logical
        hot_standby: 'on'
        wal_keep_segments: 100
        max_wal_senders: 12
        max_replication_slots: 12
        wal_log_hints: 'on'
        max_connections: '500'
  initdb: ['encoding=UTF8', 'data-checksums', 'auth-local=trust', 'locale=en_US.UTF-8', 'auth-host=md5', 'auth-local=trust']
  pg_hba: ['local all all trust', 'local replication all trust', 'host replication replication 127.0.0.1/32 trust', 'host replication replication 127.0.0.1/32 md5']
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.11.12.3:5432
  data_dir: "/data/postgresql"
  config_dir: "/etc/postgresql/12/main"
  bin_dir: "/usr/lib/postgresql/12/bin"
  use_unix_socket: True
  parameters:
    unix_socket_directories: "/var/run/postgresql"
    hba_file: "/etc/postgresql/12/main/pg_hba.conf"
    ident_file: "/etc/postgresql/12/main/pg_ident.conf"
  authentication:
    replication:
      username: replication
      password: "123"
    superuser:
      username: postgres
      password: "123"
etcd3:
  protocol: https
  cert: "/etc/ssl/patroni.pem"
  key: "/etc/ssl/patroni.key"
  cacert: "/etc/ssl/ca.pem"  
  hosts: "etcd1:2379,etcd2:2379,etcd3:2379"
watchdog:
  mode: "off"
  device: "/dev/watchdog"
  safety_margin: 5
log:
  level: "INFO"
  dir: "/var/log/patroni"
  file_num: "2"
tags:
  nofailover: False
  noloadbalance: False
  clonefrom: False
  nosync: False
```

**patronictl show-config**
```
$ patronictl edit-config
2021-08-17 16:12:42,896 - ERROR - Failed to get list of machines from https://etcd1:2379/v3: <Unknown error: 'CommonName of client sending
```

**Have you checked Patroni logs?**
```
2021-08-17 16:12:42,896 - ERROR - Failed to get list of machines from https://etcd1:2379/v3: <Unknown error: 'CommonName of client sending
```
**Have you checked PostgreSQL logs?**
n/a

**Have you tried to use GitHub issue search?**
n/a

**Additional context**
n/a

**Comment by CyberDem0n** [comment] 2021-08-17 16:27
> Expected behavior
use grpc client ?

Personally, I have neither time nor wish to work on it. Do you want to contribute the support?

**Comment by CyberDem0n** [comment] 2021-09-06 05:51
@chobostar no reaction? Then I will probably close it.

**Closed** 2021-09-06 07:01 UTC

**Comment by Magnitus-** [comment] 2022-05-21 04:30
@CyberDem0n I'll take a quick crack at it (reimplementing the etcd3 dc store) as I'm also suffering from a etcd3 problem with the current implementation in patroni (https://xx.xx.xx.xx:2379/v3 returns 404 for etcd v3.4.18). 

I get a feeling this sdk might be better for the v3 protocol: https://github.com/kragniz/python-etcd3 (though I'm not 100% certain, the Python ecosystem for etcd sdks seems to be less mature than the Golang one), but the architecture for the dcs does look non-trivial and I'm squeezed for time so if I don't get close to a working solution in 1-2 days of work, I'll reluctantly fallback to using the raft implementation instead.

**Comment by CyberDem0n** [comment] 2022-05-22 16:11
> I'm not 100% certain, the Python ecosystem for etcd sdks seems to be less mature than the Golang one

I don't know about the maturity of Golang libraries, but I certainly can tell python-etcd3 isn't in a shape that could be easily used.
Patroni needs to have full control over the retry policy: if a request to one etcd node has failed we want to switch to the next one in the cluster and retry. Of course, timeouts and the number of retries are calculated based on the topology of the Etcd cluster.
The python-etcd already implements something similar to what Patroni needs, and originally we just tried to use it as it is, but after many attempts and a few years of fixing different bugs and problems we basically ended up rewriting all methods in python-etcd responsible for HTTP communication. Also (what is very important) Patroni periodically and in case of errors updates its knowledge about the topology of the Etcd cluster (what if the node is gone forever and there is a replacement for it with a different address?).

The current implementation of Etcd v3 support (it relies on enabled gRPC-gateway) in Patroni benefits by reusing existing retry mechanisms from v2.

While it seems that python-etcd3 finally got some [support for multiple endpoints and failover](https://github.com/kragniz/python-etcd3/pull/1596) about a year ago, it never made it to a release and hence probably neither used nor tested by enough people.

You may run raft at your own risk, or just enable gRPC-gateway in etcd, which seems to be not enabled when etcd uses config files: https://github.com/etcd-io/etcd/issues/12093

**Comment by Magnitus-** [comment] 2022-05-25 03:09
Even after enabling the grpc gateway and switching from client certificate to username/password, there was some issues validating the etcd servers certificates (signed with an internal ca).

I think I'm having enough issues with that I'll give the grpc plugin / golang proxy integration a serious try (I think the golang etcd integration is just orders of magnitude better at this point). I started on that today, but there is a lot of complexity to extrapolate from the DCs implementations (the comments help a lot, but a lot of information is still missing) so I'll do what is best for the immediate interests of my employer by moving the timeline for this endeavor to medium/long term and will instead focus my immediate efforts to continuous archiving.

Having full ha would be ideal, but for now, we'll settle for making data loss if a disk goes bust negligible and otherwise opting for a manual restore.

**Comment by CyberDem0n** [comment] 2022-05-25 06:17
> there was some issues validating the etcd servers certificates (signed with an internal ca).

I am pretty sure specifying `etcd3.cacert` would solve them.

> to give the grpc plugin / golang proxy integration a serious try

Well, please also keep in mind that every additional layer increases complexity and hence reduces reliability.

**Comment by Magnitus-** [comment] 2022-05-25 14:04
> I am pretty sure specifying `etcd3.cacert` would solve them.

Yes, I did that:
https://github.com/Ferlab-Ste-Justine/kvm-postgres-server/blob/feature/patroni-integration/files/user_data.yaml.tpl#L62
https://github.com/Ferlab-Ste-Justine/kvm-postgres-server/blob/feature/patroni-integration/files/patroni.yml.tpl#L21

Still no success.

> Well, please also keep in mind that every additional layer increases complexity and hence reduces reliability.

Yes, it's a tradeoff, but I think decoupling parts of the app with grpc (something I believe Terraform is doing with its providers) has some serious merit to decouple things here and help with the integration of other languages.

I think a well coded lightweight Golang process managed by systemd with restarts and grpc (a fairly performance protocol compared to REST) on the same node Postgres/Patroni is running would be a reasonable tradeoff.

**Comment by CyberDem0n** [comment] 2022-05-25 14:20
```
  #Etcd certs
  - path: /opt/etcd/ca.pem
    owner: root:root
    permissions: "0400"
```

It is owned by root with read-only permissions given to root only, Patroni simply can't read it.

**Comment by Magnitus-** [comment] 2022-05-25 15:03
> ```
>   #Etcd certs
>   - path: /opt/etcd/ca.pem
>     owner: root:root
>     permissions: "0400"
> ```
> 
> It is owned by root with read-only permissions given to root only, Patroni simply can't read it.

Seems like a strong candidate indeed for the problem, well spotted, thanks. I'll assist some devs with their integrations and then try a couple of things for the certificate (this and making 100% sure the entire certificate chain is there, I know some apps are finicky about that).

**Comment by Magnitus-** [comment] 2022-05-26 15:10
@CyberDem0n I can confirm that the latest rounds of problems were due to the configuration of etcd:
https://github.com/Ferlab-Ste-Justine/kvm-etcd-server/commit/064c42d19cb6e877aecc7baf3437b7cfc2ca52e0
https://github.com/Ferlab-Ste-Justine/kvm-etcd-server/commit/13833b4c2ece1f4fbe354556a1a93f274bdd3e4f

This is new territory for me as I've never had to user password authentication with etcd, but my empirical observation so far appear to indicate that password that password and certificate authentication in etcd are an xor, you use one or the other, but not both.

With that out of the way, Patroni is now successfully talking to etcd. Thanks for your help.
