### ISSUE TITLE
Patroni 1.5.6 with etcd 3.4 error

### ISSUE THREAD

**Issue by travislai39** [zalando/patroni#1163] opened 2019-09-02 22:17 UTC
Please help...how to config patroni to use etcd api v3.  ETCD 3.4 default is api v3.
Thanks,
-----------------------
etcdctl version: 3.4.0
API version: 3.4
----------------------------------------
patroni.yml
scope: postgres
namespace: /abc/
name: test

restapi:
    listen: 10.0.0.10:8008
    connect_address: 10.0.0.10:8008

etcd:
    host: 10.0.0.50:2379
----------------------------------------
2019-09-02 15:14:18,723 ERROR: Failed to get list of machines from http://10.0.0.50:2379/v2: MaxRetryError("HTTPConnectionPool(host='...
2019-09-02 15:14:18,724 INFO: waiting on etcd
----------------------------------------

**Comment by bradnicholson** [comment] 2019-09-02 22:50
You will need to enable the etcd v2 API.  Etcd 3.4 turned it off by default.
 
https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md#make-etcd---enable-v2false-default

**Comment by travislai39** [comment] 2019-09-02 23:01
Thanks bradnicholson for your comment.  it's sad to know that Patroni doesn't currently support the v3 API.  ETCD is now default as api v3.  v2 api is legacy.

**Comment by travislai39** [comment] 2019-09-02 23:05
@bradnicholson : is this the right way to enable namespace for etcd in patroni.yml file
scope: helloworld
namespace: /abc/
name: test

Thanks

**Comment by CyberDem0n** [comment] 2019-09-05 09:05
@travislai39, @bradnicholson there is a [pull request](https://github.com/zalando/patroni/pull/1162) implementing support of etcd v3 protocol: https://github.com/zalando/patroni/pull/1162

If you have spare time it would be great if you try it.
In the patroni.yaml you have to rename `etcd` to `etcd3`, all other parameters stay the same.

**Comment by bradnicholson** [comment] 2019-09-06 00:19
@CyberDem0n I will give it a shot tomorrow or early next week.

Anything in particular you want us to test beyond regular usage and failure conditions?

**Comment by bradnicholson** [comment] 2020-02-26 16:26
I've found some  time to test this.  Testing with a cluster of 3x etcd v3.2.7 members and Postgres 11.5.  Etcd connection is via a SRV record.  I did not test with individual etcd host names.

I can also test with PG 12 if you think any of the changes in PG 12 might be affected here (I doubt it - but let me know)

Here's what I've found so far:

- Controlled start/stop of etcd members, ensuring quorum is maintained.  etcd reconnections to other members happen as expected, no interruption to Postgres.
- breaking quorum by stopping the two etcd members that Patroni is not connected to works as intended.  However, it does throw a big stack trace when it happens as below.  When etcd quorum is restored, Postgres goes back to read/write mode as expected.

Stack trace from when quorum is broken:

```
2020-02-26 15:26:58,411 ERROR: Request to server http://etcd-m-2:2379 failed: ReadTimeoutError("HTTPConnectionPool(host='etcd-m-2', port=2379): Read timed out. (read timeout=3.3333333333333335)",)
2020-02-26 15:26:58,411 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:26:58,411 INFO: Selected new etcd server http://etcd-m-1:2379
2020-02-26 15:26:58,413 ERROR: KVCache.run ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2020-02-26 15:26:58,415 ERROR: Request to server http://etcd-m-1:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-1', port=2379): Max retries exceeded with url: /v3alpha/lease/keepalive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474c160>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:26:58,415 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:26:58,415 INFO: Selected new etcd server http://etcd-m-0:2379
2020-02-26 15:26:58,418 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/lease/keepalive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd472ec18>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:26:58,418 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:26:58,418 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:00,762 ERROR: Request to server http://etcd-m-2:2379 failed: ReadTimeoutError("HTTPConnectionPool(host='etcd-m-2', port=2379): Read timed out. (read timeout=2.157813231150309)",)
2020-02-26 15:27:00,762 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:00,762 INFO: Selected new etcd server http://etcd-m-1:2379
2020-02-26 15:27:00,764 ERROR: KVCache.run ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2020-02-26 15:27:00,768 ERROR: Request to server http://etcd-m-1:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-1', port=2379): Max retries exceeded with url: /v3alpha/lease/keepalive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474cba8>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:00,768 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:00,768 INFO: Selected new etcd server http://etcd-m-0:2379
2020-02-26 15:27:00,770 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/lease/keepalive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474c550>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:00,770 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:00,771 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:01,767 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474c860>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:01,769 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474c4a8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:01,770 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/kv/range (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474cb00>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:01,770 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:01,770 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:02,563 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd4737cf8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:02,563 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd47375f8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:02,565 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/kv/range (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd476bba8>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:02,565 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:02,565 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:02,827 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd474c668>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:02,828 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd476bf28>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:02,828 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/kv/range (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd476b6a0>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:02,828 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:02,829 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:02,879 ERROR: Request to server http://etcd-m-0:2379 failed: ReadTimeoutError("HTTPConnectionPool(host='etcd-m-2', port=2379): Read timed out. (read timeout=1.100298007329305)",)
2020-02-26 15:27:02,880 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:02,880 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:03,784 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd46cd048>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:03,786 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd46cd0f0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:03,789 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/kv/range (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd46cd278>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:03,789 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:03,790 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:04,772 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd476bf28>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:04,773 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd4737e80>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v3alpha/kv/range
2020-02-26 15:27:04,773 ERROR: Request to server http://etcd-m-0:2379 failed: MaxRetryError("HTTPConnectionPool(host='etcd-m-0', port=2379): Max retries exceeded with url: /v3alpha/kv/range (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cd4737d68>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
2020-02-26 15:27:04,774 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:04,774 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:05,080 ERROR: Request to server http://etcd-m-0:2379 failed: ReadTimeoutError("HTTPConnectionPool(host='etcd-m-2', port=2379): Read timed out. (read timeout=1.411813735961914)",)
2020-02-26 15:27:05,080 INFO: Reconnection allowed, looking for another server.
2020-02-26 15:27:05,080 ERROR: Machines cache is empty, no machines to try.
2020-02-26 15:27:05,080 ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd.py", line 205, in _do_http_request
    response = request_executor(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='etcd-m-2', port=2379): Read timed out. (read timeout=1.411813735961914)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 828, in _next_server
    mach = self._machines_cache.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd.py", line 525, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd3.py", line 755, in _update_leader
    elif self.retry(self._client.lease_keepalive, self._lease):
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd.py", line 406, in retry
    return retry(*args, **kwargs)
  File "/home/ibm/python/site-packages/src/patroni/patroni/utils.py", line 331, in __call__
    return func(*args, **kwargs)
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd3.py", line 317, in lease_keepalive
    return self.call_rpc('/lease/keepalive', {'ID': ID}, retry).get('result', {}).get('TTL')
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd3.py", line 538, in call_rpc
    ret = super(PatroniEtcd3Client, self).call_rpc(method, fields, retry)
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd3.py", line 260, in call_rpc
    return self.api_execute(self.version_prefix + method, self._MPOST, fields)
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd.py", line 247, in api_execute
    response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd.py", line 218, in _do_http_request
    self._base_uri = self._next_server(cause=e)
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd3.py", line 511, in _next_server
    ret = super(PatroniEtcd3Client, self)._next_server(cause)
  File "/home/ibm/python/site-packages/src/patroni/patroni/dcs/etcd.py", line 196, in _next_server
    return super(AbstractEtcdClientWithFailover, self)._next_server(cause)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 832, in _next_server
    cause=cause)
etcd.EtcdConnectionFailed: No more machines in the cluster
2020-02-26 15:27:05,107 ERROR: Error communicating with DCS
```

Performing a rolling upgrade of etcd doesn't fair as well - depending on the ordering of the rolls. etcd is running in k8s pods, rolling update involves deleting the etcd pods one at a time (ensuring quorum is never broken).  Doing so, each gets a new IP address.  We don't specify IPs in the config as mentioned earlier (we use an SRV record)

- If the etcd member Patroni is connected is rolled last, the machine cache is stale, and Patroni can't reconnect to any other members.  It also can't connect to the same member it was previously connected to when that member comes back.  Postgres is in read-only mode for 5 minutes until the timeout is hit and the cache refreshes.  Then Postgres comes back with read/write.  I'm wondering if trying a single refresh of the cache when the cache is exhausted is possible here?  Also, this is not a regression from the v2 API.  v2 has the same condition.
- If the etcd member Patroni is connected to is rolled first or second, Patroni is able to reconnect and there is no outage.  Presumably, the machine cache is refreshed on the reconnection, and etcd has one member with the new IP that it can connect to.

I can provide logs for the above case if needed.

**Comment by CyberDem0n** [comment] 2020-08-28 10:07
Closed in https://github.com/zalando/patroni/pull/1162

**Closed by CyberDem0n** 2020-08-28 10:07 UTC

**Comment by xsKaisx** [comment] 2021-05-23 07:41
> Patroni doesn't currently support the v3 API. You will need to enable the etcd v2 API. Etcd 3.4 turned it off by default.
> 
> https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md#make-etcd---enable-v2false-default

I have the same issue and the link is not available

**Comment by hschoenh** [comment] 2022-03-21 15:13
Hi,
i run into this error when starting patroni, any advises?

patroni[6864]: ERROR: Failed to get list of machines from localhost:2379/v2: EtcdException('Bad response : 404 page not found\n',)
patroni[6864]: INFO: waiting on etcd

etcd Version: 3.5.2
patroni 2.1.3
