### ISSUE TITLE
cannot execute SQL commands in WAL sender for physical replication

### ISSUE THREAD

**Issue by nb-jl** [zalando/patroni#1977] opened 2021-06-22 06:42 UTC
Can you help with this errors: 
cannot execute SQL commands in WAL sender for physical replication - LEADER

Follower:
ERROR: Exception when working with master via replication connection
patroni[492]: Traceback (most recent call last):
patroni[492]:   File "/usr/local/lib/python3.7/dist-packages/patroni/postgresql/rewind.py", line 188, in _check_timeline_and_Jun patroni[492]:     cur.execute('IDENTIFY_SYSTEM')
patroni[492]: psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication
patroni[492]: 2021-06-22 02:41:01,273 INFO: no action.  i am a secondary and i am following a leader

**Comment by CyberDem0n** [comment] 2021-06-22 06:45
Duplicate of https://github.com/zalando/patroni/issues/1969

**Closed by CyberDem0n** 2021-06-22 06:45 UTC
