### ISSUE TITLE
Using "Permanent Slots" still allows for removal of slots

### ISSUE THREAD

**Issue by aliasdhacker** [zalando/patroni#1267] opened 2019-11-05 14:08 UTC
When configuring the slots in our instance we notice that they are being removed by patroni, even if we configure permanent slots.  Is this expected behavior or a bug?

Here is the configuration we are using for slots:
  slots:
     postgresql_oss_pgXXY:
          type: physical
     postgresql_oss_pgXXX:
          type: physical

**Comment by aliasdhacker** [comment] 2019-11-05 14:18
Note: This behavior is not consistent.

**Comment by CyberDem0n** [comment] 2019-11-10 11:18
I don't really get what you mean.
Have you used `patronictl edit-config` to configure slots?

**Comment by wcrowell** [comment] 2019-11-12 03:47
He's saying that when they are configured in patroni.yml, then Patroni never creates the slots on startup.

**Comment by CyberDem0n** [comment] 2019-11-12 13:50
Slots are configured for the whole cluster in DCS.
In order to change/reconfigure them you have to use `patronictl edit-config`

**Comment by wcrowell** [comment] 2019-11-12 19:50
Just for clarification, when the master/primary goes down for whatever reason is the slot copied from the master over to the newly elected/promoted primary?  Thanks for your response.

**Comment by wcrowell** [comment] 2019-11-13 00:15
Just a clarification on this, if you create a permanent physical slot and the primary/master goes down, then is the replication slot copied to the new promoted primary/master?

**Comment by CyberDem0n** [comment] 2019-11-13 08:22
> is the slot copied from the master over to the newly elected/promoted primary?

The slot will be _created_ on the new primary.

**Comment by wcrowell** [comment] 2019-11-13 09:32
We are taking over a standalone PostgreSQL 11.5 server and adding it into a Patroni cluster: [https://patroni.readthedocs.io/en/latest/existing_data.html](https://patroni.readthedocs.io/en/latest/existing_data.html)
We still see that the replication slot being deleted.  We defined a permanent slot in the postgres0.yml, but they are not getting created.  

In failover situations the slot seems to be disappearing.

**Comment by CyberDem0n** [comment] 2019-11-13 14:00
1. So far I haven't seen your config file, but I can imagine that you are trying to change the bootstrap section.
2. If you are trying to change the bootstrap section after the cluster was initialized - that won't work.

**Comment by wcrowell** [comment] 2019-11-13 15:54
Yes, I am trying to change the bootstrap section.  So I did wipe out my 3 Postgres servers as well as what was in etcd.   The replication slot was persisted at first, but when I did a switchover/failover it was lost.  Thanks for looking at this.

[postgres2.txt](https://github.com/zalando/patroni/files/3842099/postgres2.txt)
[postgres1.txt](https://github.com/zalando/patroni/files/3842100/postgres1.txt)
[postgres0.txt](https://github.com/zalando/patroni/files/3842101/postgres0.txt)

**Comment by CyberDem0n** [comment] 2019-11-13 16:39
All these files doesn't look like a valid YAML files...
Ok, lets assume that they were damaged during copy&paste or something like this.
Could you please show the output of `patronictl -c postgres0.yml show-config`?

**Comment by wcrowell** [comment] 2019-11-13 17:02
Sorry about that.  Here it is:

./patronictl.py -c postgres0.yml show-config

loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  bills_slot:
    type: physical
ttl: 30

**Comment by CyberDem0n** [comment] 2019-11-13 17:14
Looks good, everything should work.
If it doesn't - please enable debug logs and check logs of Patroni and posgres

**Comment by wcrowell** [comment] 2019-11-13 20:00
Attached.

[postgres0.log](https://github.com/zalando/patroni/files/3843216/postgres0.log)
[postgres1.log](https://github.com/zalando/patroni/files/3843217/postgres1.log)
[postgres2.log](https://github.com/zalando/patroni/files/3843218/postgres2.log)

**Comment by CyberDem0n** [comment] 2019-11-13 20:03
Well, I actually meant that you should analyse them...

**Comment by wcrowell** [comment] 2019-11-13 20:19
Ok, I will analyze them, but I do think this is a serious bug that others should look at this as well.  I did follow issue: [https://github.com/zalando/patroni/issues/656](https://github.com/zalando/patroni/issues/656)

And the resulting PR from it: [https://github.com/zalando/patroni/pull/819](https://github.com/zalando/patroni/pull/819)

This enhancement did not work.

**Comment by CyberDem0n** [comment] 2019-11-13 20:27
Feature works exactly as advertised and more over, we run integration tests for every commit to make sure that it works.

**Comment by wcrowell** [comment] 2019-11-13 20:30
I beg to differ here.  I have a simple setup of 3 Postgres servers on a single Vagrant CentOS 7 instance with etcd.  It does create the slot when you initially bring up the cluster.  You switchover or failover, and the slot is gone.  Your test cases do not have enough coverage.  This is easily reproducible.

**Comment by CyberDem0n** [comment] 2019-11-13 20:58
```bash
$ docker-compose up -d
Creating demo-haproxy ... 
Creating demo-patroni1 ... 
Creating demo-etcd1 ... 
Creating demo-etcd2 ... 
Creating demo-patroni2 ... 
Creating demo-patroni3 ... 
Creating demo-etcd3 ... 
Creating demo-haproxy
Creating demo-etcd1
Creating demo-patroni1
Creating demo-patroni2
Creating demo-etcd3
Creating demo-etcd2
Creating demo-etcd3 ... done

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
6c2d96382da4        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 4 seconds                                           demo-etcd2
e2b508044d79        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 5 seconds                                           demo-patroni3
0ba83071e25a        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 6 seconds                                           demo-patroni2
6ecab55782f4        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 3 seconds                                           demo-etcd3
fccbcc078b55        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 5 seconds                                           demo-patroni1
d0b5b113eb04        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 6 seconds                                           demo-etcd1
30ba7cd2fe26        patroni             "/bin/sh /entrypoint…"   8 seconds ago       Up 4 seconds        0.0.0.0:5000-5001->5000-5001/tcp   demo-haproxy

$ docker exec -ti demo-patroni1 bash
postgres@patroni1:~$ patronictl list
+---------+----------+------------+--------+---------+----+-----------+
| Cluster |  Member  |    Host    |  Role  |  State  | TL | Lag in MB |
+---------+----------+------------+--------+---------+----+-----------+
|   demo  | patroni1 | 172.21.0.2 | Leader | running |  1 |         0 |
|   demo  | patroni2 | 172.21.0.6 |        | running |  1 |         0 |
|   demo  | patroni3 | 172.21.0.5 |        | running |  1 |         0 |
+---------+----------+------------+--------+---------+----+-----------+
postgres@patroni1:~$ patronictl edit-config
--- 
+++ 
@@ -10,3 +10,6 @@
   use_pg_rewind: true
 retry_timeout: 10
 ttl: 30
+slots:
+  foo:
+    type: physical

Apply these changes? [y/N]: y
Configuration changed
postgres@patroni1:~$ psql
psql (10.10 (Debian 10.10-1.pgdg90+1))
Type "help" for help.

postgres=# select * from pg_replication_slots;
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
 patroni3  |        | physical  |        |          | f         | t      |         64 |      |              | 0/4000548   | 
 patroni2  |        | physical  |        |          | f         | t      |         62 |      |              | 0/4000548   | 
 foo       |        | physical  |        |          | f         | f      |            |      |              | 0/20000D0   | 
(3 rows)

postgres=# \q
postgres@patroni1:~$ patronictl switchover
Master [patroni1]: 
Candidate ['patroni2', 'patroni3'] []: 
When should the switchover take place (e.g. 2019-11-13T21:52 )  [now]: 
Current cluster topology
+---------+----------+------------+--------+---------+----+-----------+
| Cluster |  Member  |    Host    |  Role  |  State  | TL | Lag in MB |
+---------+----------+------------+--------+---------+----+-----------+
|   demo  | patroni1 | 172.21.0.2 | Leader | running |  1 |         0 |
|   demo  | patroni2 | 172.21.0.6 |        | running |  1 |         0 |
|   demo  | patroni3 | 172.21.0.5 |        | running |  1 |         0 |
+---------+----------+------------+--------+---------+----+-----------+
Are you sure you want to switchover cluster demo, demoting current master patroni1? [y/N]: y
2019-11-13 20:52:21.83173 Successfully switched over to "patroni3"
+---------+----------+------------+--------+---------+----+-----------+
| Cluster |  Member  |    Host    |  Role  |  State  | TL | Lag in MB |
+---------+----------+------------+--------+---------+----+-----------+
|   demo  | patroni1 | 172.21.0.2 |        | stopped |    |   unknown |
|   demo  | patroni2 | 172.21.0.6 |        | running |    |   unknown |
|   demo  | patroni3 | 172.21.0.5 | Leader | running |  1 |           |
+---------+----------+------------+--------+---------+----+-----------+
postgres@patroni1:~$ exit
$ docker exec -ti demo-patroni3 bash
postgres@patroni3:~$ psql
psql (10.10 (Debian 10.10-1.pgdg90+1))
Type "help" for help.

postgres=# select * from pg_replication_slots ;
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
 foo       |        | physical  |        |          | f         | f      |            |      |              | 0/4000690   | 
 patroni1  |        | physical  |        |          | f         | t      |        127 |      |              | 0/4000770   | 
 patroni2  |        | physical  |        |          | f         | t      |        130 |      |              | 0/4000770   | 
(3 rows)

postgres=# \q
postgres@patroni3:~$ exit
```

Do you need more proof that it works?

**Comment by wcrowell** [comment] 2019-11-13 21:05
Give me a bit, and I'll share the output I have.

**Comment by wcrowell** [comment] 2019-11-14 06:02
I attached the sequence with what I ran including the Postgres command to check the slots.  What is interesting is that it is not doing it all the time.  It sometimes does it like 1 out of 4 or 5 times.  So I keep switching and failing over and testing it.  It always happens on the first time I switchover.

[patroni-debugging.txt](https://github.com/zalando/patroni/files/3844822/patroni-debugging.txt)

**Comment by CyberDem0n** [comment] 2019-11-14 07:00
```
psql -h 127.0.0.1 -U postgres
psql (12.0)
Type "help" for help.

postgres=# select * from pg_replication_slots;
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
(0 rows)
```

Really? Have you noticed that the new master is running on port 5433?

**Comment by wcrowell** [comment] 2019-11-14 07:41
Point noted.  
1) Do you know why the active column is false for the custom permanent physical slot?  I see that the active column for the slots on the slave nodes are true.
2) Can we also use the use_slots setting together with permanent physical slots?  I believe the use_slots just creates the slots on the slave nodes only. 

If you could help me understand that, then I would appreciate it.

**Comment by CyberDem0n** [comment] 2019-11-14 08:12
> why the active column is false for the custom permanent physical slot?

Because nobody is using it.

> I see that the active column for the slots on the slave nodes are true.

There are no slaves in postgres. The slot is active because replicas are streaming from the primary.

> Can we also use the use_slots setting together with permanent physical slots?

The `use_slots` option enables or disables the usage of replication slots for the whole cluster.

I would recommend you to read the postgres documentation: https://www.postgresql.org/docs/current/warm-standby.html#STREAMING-REPLICATION

**Comment by wcrowell** [comment] 2019-11-18 13:08
You can close this issue.  I work with the requester, aliasdhacker, and I feel confident about the answers given in this ticket.

**Closed** 2019-12-03 08:32 UTC
