### ISSUE TITLE
Failover doesn't occur when consul node under the leader is stopped

### ISSUE THREAD

**Issue by maksm90** [zalando/patroni#1054] opened 2019-05-08 09:37 UTC
Hello everyone!
My problem is similar to #251 but for synchronous replication.

Since patroni bot can communicate with single consul node the autofailover process is sensible to heath of consul node with which patroni leader interacts.

My case is following:

- cluster consists of three nodes

- on each node the consul server agent is deployed

- on two nodes patroni bots (and PostgreSQL instances) are started and communicate with local consul agents

- synchronous replication is established (`synchronous_mode_strict: off`).

After disabling consul agent under the leader patroni bot this one demotes itself (flip to read-only mode) but another patroni node cannot be promoted because it lags in wal position from master - the message **INFO: Wal position of <master_node> is ahead of my wal position** appears in log.

I think this issue is bug because the patroni bot isolated from DCS participates in leader election procedure (shares own wal position when it is not neccessary) and doesn't allow other synchronous replica to promote. 

Patroni version is 1.5.6.

**Comment by CyberDem0n** [comment] 2019-05-08 10:09
The former master doesn't really participate in the leader race, but it still responds on REST API requests.
For the asynchronous replication,  that would be correct behavior. The node disqualifies itself from the leader race if it knows that some other node is ahead in WAL position.

Synchronous mode is a different beast. We still want to make sure that the old master is not running as a master anymore, but the synchronous replica can safely ignore WAL position check, because we know for sure that it has all **transactions** which were reported to the client as committed.

@ants what do you think?

**Comment by ants** [comment] 2019-05-08 20:23
To be more accurate, the sync standby will have all transactions that the client has requested sync replication for. But indeed it seems like a good idea to always allow promotion when we know we are in sync. I was not brave enough to go that far with the initial patch, but in hindsight I can't imagine a situation where this safeguard would save us and we have a (semi) realistic scenario where it prevents a valid failover.

Something to think about - maybe we want to do the same thing in async mode too, if we know that the node that is ahead doesn't have access to the DCS. The desired availability/durability tradeoff is less clear in async mode.

**Comment by chobostar** [comment] 2019-05-13 09:16
> maybe we want to do the same thing in async mode too, if we know that the node that is ahead doesn't have access to the DCS. The desired availability/durability tradeoff is less clear in async mode.

Sounds like a expected behavior for me, exceptionally if it's under `maximum_lag_on_failover`. 

I met the same issue in async mode, Patroni stucks in loop with `INFO: Wal position of <old_master> is ahead of my wal position` and failover doesn't occur

**Comment by CyberDem0n** [comment] 2019-05-13 10:58
I prepared a PR fixing the leader race in synchronous mode.

With async mode it is not that trivial and requires some refactoring:
1. We can easily catch the case when DCS is not accessible for reads, but in case of network partitioning it could be possible that only writes are failing.
2. We need to expose `dcs_failed` field in the REST API.
3. We need to define a new setting which will trigger the new behavior.

The most problematic part is the refactoring of DCS and I am not sure that it is currently worth the time.

**Closed** 2019-05-13 14:32 UTC

**Comment by maksm90** [comment] 2019-05-13 16:46
Hi @CyberDem0n!
Thanks for PR fixing my issue. I'll apply and test this fix soon.

Some questions and notes from me regarding this PR:

> We can easily catch the case when DCS is not accessible for reads, but in case of network partitioning it could be possible that only writes are failing.

Do you use only stale read from DSC (from not leader node in case of Raft)? I think it makes sense to use some periodic quorum checks to DCS for each patroni bot.

> We need to expose dcs_failed field in the REST API.

IMO the best strategy here is to require the node that returns true value of `dcs_failed` as failed (not accessible for others) in the procedure of wal position exchange so that other nodes participate in the leader race without regard to isolated master.

**Comment by konst583** [comment] 2019-05-13 20:17
> I prepared a PR fixing the leader race in synchronous mode.
> 
> With async mode it is not that trivial and requires some refactoring:
> 
>     1. We can easily catch the case when DCS is not accessible for reads, but in case of network partitioning it could be possible that only writes are failing.
> 
>     2. We need to expose `dcs_failed` field in the REST API.
> 
>     3. We need to define a new setting which will trigger the new behavior.
> 
> 
> The most problematic part is the refactoring of DCS and I am not sure that it is currently worth the time.

Even using synchronous replication for more than 1 standby, it may happen that  all standbys are in different states after a crash of the primary. Synchronous replication works in such a manner: on the primary changes are committed, but there is a data structure in memory(it is not written to the WAL) that indicates that clients can’t see these changes. That indicator is stored until synchronous replicas send acknowledgement that they have successfully replayed the changes above

**Comment by CyberDem0n** [comment] 2019-05-14 13:28
> Do you use only stale read from DSC (from not leader node in case of Raft)? I think it makes sense to use some periodic quorum checks to DCS for each patroni bot.

There is not much value in quorum reads. The leader will step down if it can't write to the DCS.
