### ISSUE TITLE
Postgresql 10 Replication and patroni failover

### ISSUE THREAD

**Issue by omm1979** [zalando/patroni#1011] opened 2019-03-23 20:59 UTC
Hi, i'm asking about postgresql 10 replication and patroni failover because, i don't know if patroni do  the replication and ha failover automatically or i have to do the 2 things separately (replication, ha/failover), first do the replication with another technology and then ha/failover with patroni?, am i wrong?, because I tried first replication with any tutorial and then install and configuring patroni? or just install and configuring patroni for do 2 things (replication and ha/failover), if this last thing is true could you recommend a tutorial doing this please, thanks for your help, i'll wait for.

**Comment by mashuma** [comment] 2019-03-25 16:19
Hello @omm1979,

Maybe this will help as a quick overview of the problems Patroni solves and how does it look good doing it. https://postgresconf.org/system/events/document/000/000/228/Patroni_tutorial_4x3-2.pdf

**Comment by omm1979** [comment] 2019-03-25 17:04
Thanks for your reply, but I've review all zalando ppt's, and problem is that I have been able to make patroni work but the problem is that I do not know if the configuration of patroni is wrong or there is something I am configuring wrong in another config. file, because in all tutorials I have reviewed:
 * https://www.linode.com/docs/databases/postgresql/create-a-highly-available-postgresql-cluster-using-patroni-and-haproxy/
 * https://www.opsdash.com/blog/postgres-getting-started-patroni.html
 * https://www.ibm.com/developerworks/community/blogs/2280dc86-a78a-441b-89d7-5b4c41595852/entry/part_2_postgresHA?lang=en
 * https://blogs.sungeek.net/unixwiz/2018/09/02/centos-7-postgresql-10-patroni/
* https://www.alibabacloud.com/blog/how-to-set-up-a-highly-available-postgresql-cluster-using-patroni-on-ubuntu-16-04_594477
* and many others blogs, postgresql faq's, etc.

In those tutorials I have read that patroni automatically starts the postgresql instance without manually starting it, and I suppose this problem is related to the fact that first the postgresql replication works (without patroni installed) and patroni works run separately (replication stop working with patroni installed). In fact I will leave the output of the registry files of postgres and patroni, in addition to the syslog of linux.

_____________________________________________
patronix.yml (node 1 and just changing IP addresses)

[patroni.yml.txt](https://github.com/zalando/patroni/files/3004549/patroni.yml.txt)
_____________________________________________
postgtresql.conf

[postgresql.conf.txt](https://github.com/zalando/patroni/files/3004550/postgresql.conf.txt)
_____________________________________________
pg_hba.conf

[pg_hba.conf.txt](https://github.com/zalando/patroni/files/3004552/pg_hba.conf.txt)
_____________________________________________
etcd config

[etcd.txt](https://github.com/zalando/patroni/files/3004554/etcd.txt)
_____________________________________________
postgresql-10-main.log

[postgresql-10-main.log.txt](https://github.com/zalando/patroni/files/3004519/postgresql-10-main.log.txt)
_____________________________________________
/data/patroni/pg_log/postgresql-2019-03-25_103112.log

[postgresql-2019-03-25_103112.log.txt](https://github.com/zalando/patroni/files/3004532/postgresql-2019-03-25_103112.log.txt)
_____________________________________________
syslog

[syslog.txt](https://github.com/zalando/patroni/files/3004534/syslog.txt)
_____________________________________________

I hope this could help, and there is some progress with this, thanks a lot and regards.

**Comment by omm1979** [comment] 2019-03-25 22:59
I don't know if this subject (trouble) is misunderstood, because my main problem is that postgresql isn't doing database replication to the slaves nodes, do i clarify this subject? or is unclear? thanks.

**Comment by CyberDem0n** [comment] 2019-03-26 08:47
I am closing this issue as a duplicate of #1012.

**Closed by CyberDem0n** 2019-03-26 08:47 UTC
