### ISSUE TITLE
psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication

### ISSUE THREAD

**Issue by bimcas** [zalando/patroni#1985] opened 2021-06-28 10:39 UTC
**Environment**
- Python version: 3.6.8
- Patroni version: 2.0.2
- PostgreSQL version: 12.7

**Describe the bug**
After updating **psycopg2-binary** to **2.9.1** version I'm getting error messages on Replica (Stand-by) nodes in Patroni log:

Jun 28 12:02:57 patroni[4817]: psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,203 INFO: Lock owner: node001; I am node002
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,203 INFO: does not have lock
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,204 INFO: Local timeline=15 lsn=18BA/A7647FB8
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,226 ERROR: Exception when working with master via replication connection
Jun 28 12:02:58 patroni[4817]: Traceback (most recent call last):
Jun 28 12:02:58 patroni[4817]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 188, in _check_timeline_and_lsn
Jun 28 12:02:58 patroni[4817]: cur.execute('IDENTIFY_SYSTEM')
Jun 28 12:02:58 patroni[4817]: psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,264 INFO: no action.  i am a secondary and i am following a leader
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,286 ERROR: Can not fetch local timeline and lsn from replication connection
Jun 28 12:02:58 patroni[4817]: Traceback (most recent call last):
Jun 28 12:02:58 patroni[4817]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 738, in get_replica_timeline
Jun 28 12:02:58 patroni[4817]: cur.execute('IDENTIFY_SYSTEM')
Jun 28 12:02:58 patroni[4817]: psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication
Jun 28 12:02:58 patroni[4817]: 2021-06-28 12:02:58,287 ERROR: Can not fetch local timeline and lsn from replication connection

**No such error messages in patroni log on Leader node, just on Replica (Stand-by).** 

But I see error messages in postgresql logs of all nodes: Leader and Replicas:

2021-06-28 10:25:28.754 UTC,"replication","",ERROR,XX000,"cannot execute SQL commands in WAL sender for physical replication",,,,,,,,,""
2021-06-28 10:25:29.760 UTC,"replication","",ERROR,XX000,"cannot execute SQL commands in WAL sender for physical replication",,,,,,,,,""
2021-06-28 10:25:29.761 UTC,"replication","",ERROR,XX000,"cannot execute SQL commands in WAL sender for physical replication",,,,,,,,,""

**Despite the error in logs, all nodes are running in the cluster, I can failover.**

**To Reproduce**
Update **psycopg2-binary** to **2.9.1**. 

**Expected behavior**
When I rollback psycopg2-binary to 2.8.6 version, I don't have suck error messages in patroni and postgresql logs

**Comment by CyberDem0n** [comment] 2021-06-28 10:41
Duplicate of #1977, #1969, #1979, and #1980

**Closed by CyberDem0n** 2021-06-28 10:41 UTC
