### ISSUE TITLE
Api init Cannot assign requested address

### ISSUE THREAD

**Issue by climb2211** [zalando/patroni#2709] opened 2023-06-07 03:05 UTC
### What happened?

When the k8s pod is created, but before the network is configured, if the patroni api is initialized, there will be a small probability of Cannot assign requested address error.

### How can we reproduce it (as minimally and precisely as possible)?

Because this is a random problem and it is difficult to reproduce, so I didn't find a better way

### What did you expect to happen?

patroni api can start normally

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.0.2
-   PostgreSQL version: 10
-   DCS (and its version):  kubernetes dcs

### Patroni configuration file

```yaml
bootstrap:
  dcs:
     synchronous_mode: true
  watchdog:
     mode: off
```

### patronictl show-config

```yaml
N/A
```

### Patroni log files

```shell
ERROR: Couldn't start a service on 'localhost:8008', please check your `restapi.listen` configuration, address_family = AddressFamily.AF_INET
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/postgresql/patroni/__init__.py", line 221, in patroni_main
    patroni = Patroni(conf)
  File "/var/lib/postgresql/patroni/__init__.py", line 34, in __init__
    self.api = RestApiServer(self, self.config['restapi'])
  File "/var/lib/postgresql/patroni/api.py", line 492, in __init__
    self.reload_config(config)
  File "/var/lib/postgresql/patroni/api.py", line 620, in reload_config
    self.__initialize(config['listen'], ssl_options)
  File "/var/lib/postgresql/patroni/api.py", line 588, in __initialize
    self.__httpserver_init(host, port)
  File "/var/lib/postgresql/patroni/api.py", line 568, in __httpserver_init
    HTTPServer.__init__(self, (host, port), RestApiHandler)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment] 2023-06-07 06:12
> When the k8s pod is created, but before the network is configured, if the patroni api is initialized, there will be a small probability of Cannot assign requested address error.

Honestly, I don't understand how is this a Patroni problem. If pod/container isn't ready yet why do you start Patroni?

> ERROR: Couldn't start a service on 'localhost:8008'

Why? REST API **must** be accessible from other nodes of the Patroni cluster. With the `localhost` it is impossible.

> Patroni version: 2.0.2

Released in Feb 2021, or more than two years ago. While the issue template is explicitly asking: `Before reporting a bug please make sure to reproduce it with the latest Patroni version!`, which is currently 3.0.2.

> PostgreSQL version: 10

EOL since November 2022.

**Comment by CyberDem0n** [comment] 2023-06-07 08:18
> because patroni is usually the number one process.

That's the problem, it shouldn't be process 1. The `init` process is very special and Patroni sort of trying to perform some of duties that init systems are doing if it is started with pid 1, but it can't do it as good as for example `dumb-init`.

> We don't config the restapi option, so it's use default configuration. Works fine in most cases

https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api:
> connect_address: IP address (or hostname) and port, to access the Patroni’s [REST API](https://patroni.readthedocs.io/en/latest/rest_api.html#rest-api). All the members of the cluster **must be able to connect** to this address, so unless the Patroni setup is intended for a demo inside the localhost, this address must be a non “localhost” or loopback address (ie: “localhost” or “127.0.0.1”).

**Comment by climb2211** [comment] 2023-06-07 09:06
sorry i  can't understand "it shouldn't be process 1",  From code in patroni/__init__.py,  

# Patroni started with PID=1, it looks like we are in the container
    pid = 0

Doesn't it mean that patroni supports the start of the first process? If we don't use patroni as the number one process, then we need our own program to have the ability to handle signals, such as container exit, etc. This creates a lot of complexity.

about localhost, yes , I notice these describe in the document,  But I don't think it should be an explanation for not supporting localhost. Normally, it can also be used in the demo, but this error will appear under abnormal circumstances

**Comment by CyberDem0n** [comment] 2023-06-07 09:13
JFYI:
https://github.com/zalando/patroni/issues/2351#issuecomment-1175961566

**Comment by climb2211** [comment] 2023-06-08 02:50
Ok, I understand for this , but no matter whether we wrap patroni with other init process,  doesn't patroni consider some scenarios where initialization fails? like cannot assign requested address. etc. If we add some exception processing for these scenarios, it should improve the robustness of patroni.

Thanks.

**Comment by CyberDem0n** [comment] 2023-06-20 06:55
If it failed on start maybe we can just exit.
But, the same method might be called on reload, when for example `restapi.listen` was changed, or when TLS cert/key/parameters were changed. In this case consequences of exiting are much worse. We might end up without Patroni/Postgres instances running.

**Comment by CyberDem0n** [comment] 2023-07-05 06:55
Actually, I can confirm, if Patroni fails to listen on REST API port it exists with the error:
```
2023-07-05 08:54:37,357 INFO: Selected new etcd server http://localhost:2379
2023-07-05 08:54:37,364 INFO: No PostgreSQL configuration items changed, nothing to reload.
2023-07-05 08:54:37,365 ERROR: Couldn't start a service on '127.0.0.1:8008', please check your `restapi.listen` configuration
Traceback (most recent call last):
  File "/home/akukushkin/git/patroni/./patroni.py", line 6, in <module>
    main()
  File "/home/akukushkin/git/patroni/patroni/__main__.py", line 171, in main
    return patroni_main(args.configfile)
  File "/home/akukushkin/git/patroni/patroni/__main__.py", line 142, in patroni_main
    abstract_main(Patroni, configfile)
  File "/home/akukushkin/git/patroni/patroni/daemon.py", line 172, in abstract_main
    controller = cls(config)
  File "/home/akukushkin/git/patroni/patroni/__main__.py", line 37, in __init__
    self.api = RestApiServer(self, self.config['restapi'])
  File "/home/akukushkin/git/patroni/patroni/api.py", line 1259, in __init__
    self.reload_config(config)
  File "/home/akukushkin/git/patroni/patroni/api.py", line 1605, in reload_config
    self.__initialize(config['listen'], ssl_options)
  File "/home/akukushkin/git/patroni/patroni/api.py", line 1474, in __initialize
    self.__httpserver_init(host, port)
  File "/home/akukushkin/git/patroni/patroni/api.py", line 1429, in __httpserver_init
    HTTPServer.__init__(self, info[0][-1][:2], RestApiHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Closed by CyberDem0n** 2023-07-05 06:55 UTC
Labels: enhancement
