### ISSUE TITLE
"syntax error" with psycopg2 2.9.1

### ISSUE THREAD

**Issue by Vanav** [zalando/patroni#1980] opened 2021-06-23 05:40 UTC
If I update psycopg2 to version 2.9.1, Patroni and Postgres logs are filled with errors:
```
2021-06-23 08:17:04,060 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
File "/opt/pipx/venvs/patroni/lib64/python3.6/site-packages/patroni/postgresql/__init__.py", line 738, in get_replica_timeline
psycopg2.errors.SyntaxError: syntax error

2021-06-23 08:17:03,649 ERROR: Exception when working with master via replication connection
Traceback (most recent call last):
File "/opt/pipx/venvs/patroni/lib64/python3.6/site-packages/patroni/postgresql/rewind.py", line 188, in _check_timeline_and_lsn
psycopg2.errors.SyntaxError: syntax error
```

Same for psycopg2-binary. I have not found version requirements, so just installed latest available.

**Environment**
- Patroni version: 2.0.2 and 2.0.1
- PostgreSQL version: 9.6
- DCS (and its version): Consul 1.10.0

**PostgreSQL logs**
```
repluser@[unknown] ERROR:  syntax error
```

**Comment by CyberDem0n** [comment] 2021-06-23 05:41
Duplicate of #1977, #1969, and #1979

**Closed by CyberDem0n** 2021-06-23 05:41 UTC
