### ISSUE TITLE
All hosts are slaves

### ISSUE THREAD

**Issue by petqa** [zalando/patroni#2140] opened 2021-12-09 13:12 UTC
**Describe the bug**
Greetings, after trying to switch the slave to another master, we get a 503 error.
After that we get all hosts marked as slaves.

**To Reproduce**
Create 4 databases, 2 of them cannot become masters and try to do a switchover.

**Expected behavior**
Slave must become a master.

**Screenshots**
```
+ Cluster: postgres (6992523898558255339) -------+---------+-----+-----------+-------------------------+
| Member           | Host              | Role    | State   |  TL | Lag in MB | Tags                    |
+------------------+-------------------+---------+---------+-----+-----------+-------------------------+
| another-first-1  | 192.168.0.1:5435  | Replica | running | 153 |         0 | nofailover: true        |
|                  |                   |         |         |     |           | replicatefrom: first-1  |
+------------------+-------------------+---------+---------+-----+-----------+-------------------------+
| another-second-2 | 192.168.0.2:5435  | Replica | running | 153 |         0 | nofailover: true        |
|                  |                   |         |         |     |           | replicatefrom: second-2 |
+------------------+-------------------+---------+---------+-----+-----------+-------------------------+
| first-1          | 192.168.0.1:5434  | Replica | running | 153 |         0 |                         |
+------------------+-------------------+---------+---------+-----+-----------+-------------------------+
| second-2         | 192.168.0.2:5434  | Replica | running | 153 |         0 |                         |
+------------------+-------------------+---------+---------+-----+-----------+-------------------------+
```

**Environment**
- patronictl version 2.1.0
- server 11.12 (Ubuntu 11.12-1.pgdg18.04+1)
- etcd 3.4.18

**Patroni configuration file**
```
scope: postgres
namespace: /local/
name: first-1
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_slots: true
      use_pg_rewind: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 5120
        max_wal_senders: 5
        max_replication_slots: 5
        checkpoint_timeout: 30S
  initdb:
  - encoding: UTF8
  - data-checksums
  - directory: /etc/postgresql/11/test2
  - pgdata: /data/11/test
  pg_hba:
  - local all all trust
  - host all all 0.0.0.0/0 md5
  - host replication patroni_replica 0.0.0.0/0 md5
  - host postgres  patroni_superuser 0.0.0.0/0 md5
  users:
    admin:
      password: admin
      options:
      - createrole
      - createdb
restapi:
  listen: "192.168.0.1:8008"
  connect_address: "192.168.0.1:8008"
etcd3:
  hosts:
  - 192.168.0.3:2379
  - 192.168.0.4:2379
  - 192.168.0.5:2379
postgresql:
  listen: 192.168.0.1:5434
  connect_address: 192.168.0.1:5434
  data_dir: /data/11/test
  bin_dir: /usr/lib/postgresql/11/bin
  config_dir: /etc/postgresql/11/test
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: patroni_replica
      password: patroni_replica
    superuser:
      username: patroni_superuser
      password: patroni_superuser
    create_replica_methods:
      basebackup:
        checkpoint: 'fast'
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
    log_destination: csvlog
    log_directory: '/data/logs'
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_line_prefix: '%m  %p %u@%d from %h [vxid:%v txid:%x] [%i]'
    log_min_duration_statement: '1000'
    log_rotation_age: 2d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    max_connections: "1000"
    shared_buffers: "8GB"
    work_mem: "32MB"
    maintenance_work_mem: "2GB"
    parallel_leader_participation: "on"
    max_wal_size: "20GB"
    min_wal_size: "1GB"
    effective_cache_size: "96GB"
    update_process_title: "on"
    track_activities: "on"
    track_counts: "on"
    track_io_timing: "on"
    stats_temp_directory: "/var/run/postgresql/11-main.pg_stat_tmp"
    datestyle: "iso, dmy"
    timezone: "UTC"
    default_text_search_config: "pg_catalog.english"
    shared_preload_libraries: "pg_stat_statements,repmgr,pg_partman_bgw"
    deadlock_timeout: "500"
    pg_stat_statements.max: "500"
    pg_stat_statements.track: "top"
    pg_stat_statements.track_utility: "true"
    pg_stat_statements.save: "false"
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**patronictl show-config**
```
loop_wait: 5
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_timeout: 30S
    hot_standby: 'on'
    max_connections: '200'
    max_replication_slots: 5
    max_wal_senders: 5
    wal_keep_segments: 5120
    wal_level: replica
  use_slots: true
retry_timeout: 10
slots:
  test_1:
    type: physical
ttl: 20
```

**Have you checked Patroni logs?**
```
AttributeError: 'NoneType' object has no attribute 'name'
2021-12-09 13:02:20,268 INFO: Unexpected exception raised, please report it as a BUG
2021-12-09 13:02:25,294 ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1469, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1310, in _run_cycle
    self.state_handler.reset_cluster_info_state(self.cluster, self.patroni.nofailover)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 329, in reset_cluster_info_state
    cluster.has_permanent_logical_slots(self.name, nofailover, self.major_version)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 572, in has_permanent_logical_slots
    slots = self.get_replication_slots(my_name, 'replica', nofailover, major_version).values()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 518, in get_replication_slots
    slot_members = [m.name for m in self.members if use_slots and
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 519, in <listcomp>
    m.replicatefrom == my_name and m.name != self.leader.name]
AttributeError: 'NoneType' object has no attribute 'name'
2021-12-09 13:02:25,294 INFO: Unexpected exception raised, please report it as a BUG
2021-12-09 13:02:30,267 ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1469, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1310, in _run_cycle
    self.state_handler.reset_cluster_info_state(self.cluster, self.patroni.nofailover)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 329, in reset_cluster_info_state
    cluster.has_permanent_logical_slots(self.name, nofailover, self.major_version)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 572, in has_permanent_logical_slots
    slots = self.get_replication_slots(my_name, 'replica', nofailover, major_version).values()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 518, in get_replication_slots
    slot_members = [m.name for m in self.members if use_slots and
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 519, in <listcomp>
    m.replicatefrom == my_name and m.name != self.leader.name]
AttributeError: 'NoneType' object has no attribute 'name'
```

**Have you checked PostgreSQL logs?**
```
2021-12-09 12:46:10.103 UTC,,,71252,,61b1e042.11654,7,,2021-12-09 10:53:54 UTC,,0,LOG,00000,"database system is shut down",,,,,,,,,""
2021-12-09 12:46:12.645 UTC,,,5435,,61b1fa94.153b,1,,2021-12-09 12:46:12 UTC,,0,LOG,00000,"ending log output to stderr",,"Future log output will go to log destination ""csvlog"".",,,,,,,""
2021-12-09 12:46:12.648 UTC,,,5438,,61b1fa94.153e,1,,2021-12-09 12:46:12 UTC,,0,LOG,00000,"database system was shut down at 2021-12-09 12:46:09 UTC",,,,,,,,,""
2021-12-09 12:46:12.648 UTC,,,5438,,61b1fa94.153e,2,,2021-12-09 12:46:12 UTC,,0,WARNING,01000,"recovery command file ""recovery.conf"" specified neither primary_conninfo nor restore_command",,"The database server will regularly poll the pg_wal subdirectory to check for files placed there.",,,,,,,""
2021-12-09 12:46:12.648 UTC,,,5438,,61b1fa94.153e,3,,2021-12-09 12:46:12 UTC,,0,LOG,00000,"entering standby mode",,,,,,,,,""
2021-12-09 12:46:12.649 UTC,"revise","processing",5440,"192.168.0.30:41609",61b1fa94.1540,1,"",2021-12-09 12:46:12 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2021-12-09 12:46:12.652 UTC,"patroni_superuser","postgres",5439,"192.168.0.13:53962",61b1fa94.153f,1,"",2021-12-09 12:46:12 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2021-12-09 12:46:12.667 UTC,"patroni_superuser","postgres",5442,"192.168.0.13:53964",61b1fa94.1542,1,"",2021-12-09 12:46:12 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2021-12-09 12:46:12.678 UTC,"patroni_superuser","postgres",5444,"192.168.0.13:53966",61b1fa94.1544,1,"",2021-12-09 12:46:12 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2021-12-09 12:46:12.684 UTC,,,5438,,61b1fa94.153e,4,,2021-12-09 12:46:12 UTC,1/0,0,LOG,00000,"consistent recovery state reached at 9B/D065CC18",,,,,,,,,""
2021-12-09 12:46:12.684 UTC,,,5438,,61b1fa94.153e,5,,2021-12-09 12:46:12 UTC,1/0,0,LOG,00000,"invalid record length at 9B/D065CC18: wanted 24, got 0",,,,,,,,,""
2021-12-09 12:46:12.685 UTC,,,5435,,61b1fa94.153b,2,,2021-12-09 12:46:12 UTC,,0,LOG,00000,"database system is ready to accept read only connections",,,,,,,,,""
```

**Have you tried to use GitHub issue search?**
Could not find something similar.

**Additional context**
Disabling all patroni services and enabling them back brings the master back

**Comment by CyberDem0n** [comment] 2021-12-09 13:44
Duplicate of https://github.com/zalando/patroni/issues/2137

**Closed by CyberDem0n** 2021-12-09 13:44 UTC
